baseURL: "/"
languageCode: "en-us"
title: "BaseBlog | At-home lab tests and treatment plans for sleep / stress / brain fog / sex drive | get-base.com | Affordable, accessible"
pygmentsstyle: 'monokai'

# Theme settings
theme: novela
paginate: 6
social:
  twitter: "#"
  github: "#"
  instagram: "#"
  linkedin: "#"
  dribbble: "#"
  youtube: "#"
taxonomies:
  author: authors

deployment:
  targets:
    name: "mydeployment"
    URL: "s3://nesshealth.co/blog/?region=us-east-1"
  matchers:
    pattern: "^.+\\.(js|css|png|jpg|gif|svg|ttf)$"
    cacheControl: "max-age=630720000, no-transform, public"
    gzip: true